### PR TITLE
replace share method with singleton method for laravel 5.4

### PR DESCRIPTION
**Pull request by TeeeeJaaaaY**
Fixes issue #30

### CODE REVIEW

**Comment by jelovac** [comment]
Thanks for the pull request, did they change it for Laravel 4 as well, because I see that you have modified the Laravel4ServiceProvider as well?

**Comment by TeeeeJaaaaY** [comment]
No problem, From the looks of the docs it was only removed in laravel 5.4 so the modification to Laravel4ServiceProvider can be removed/ignored.

**Comment by mbarwick83** [comment]
Is this on master? I'm still getting this error. i.e. share()

**Comment by jelovac** [comment]
@mbarwick83 no it is not yet, I will test this weekend and merge into master. For now I suggest you use the TeeeeJaaaaY fork.

**Comment by jelovac** [comment]
Finally got the time to test this, was singleton introduced from 5.4 or was it available in previous 5.* versions as well?

**Comment by TeeeeJaaaaY** [comment]
Its available in 5*

**Pull request merged**
