### PR TITLE
Upgrade to Guzzle v6

### PR DESCRIPTION
**Pull request by PhiloNL**

### CODE REVIEW

**Comment by jelovac** [comment]
HI, I won't merge this for now because a lot of sites still use php 5.4 and the guzzle v6 requires 5.5.

**Comment by PallMallShow** [comment]
Why not authorize Guzzle V5 AND V6 ?
Or maybe create another branch ?

**Comment by PhiloNL** [comment]
Any update on this? Currently other packages that use V6 are forced to use V5 which is causing some issues. Any chance you could create a separate branch and release as 4.0?

**Comment by PallMallShow** [comment]
You can use my own version : https://github.com/MyoStudio/bitly4laravel/tree/fixGuzzleVersionTo6.0

**Comment by PhiloNL** [comment]
@PallMallShow Thanks

**Comment by mbarwick83** [comment]
+1 to create a separate branch for Guzzle 6. Please @jelovac 👯

**Comment by mbarwick83** [comment]
@pallmallshow how did your fork to work? I'm running Laravel 5.2.

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/MyoStudio/bitly4laravel"
    }
],
"require": {
    ...
    "jelovac/bitly4laravel": "dev-master",
}
```

**Pull request closed without merging**
