### PR TITLE
Enable Support for both Guzzle 5 and 6

### LINKED ISSUE #23: Guzzle upgrade to v6
Greetings,

This issue concerns the upgrade of Guzzle library to v6 used by this package.

The upgrade plan is the following:
- change the composer file to require v6
- migrate guzzle v5 logic to v6

rgds,
Vladimir

### PR DESCRIPTION
**Pull request by rydurham**
Fixes #23

### CODE REVIEW

**Comment by jelovac** [comment]
Hi rydurham,

Thanks for the pull request, looks ok to me.

I will test it tomorrow morning and merge it into master branch.

Best regards,
Vladimir

**Comment by inghamemerson** [comment]
@jelovac any update on merging this PR in?

**Comment by gportes** [comment]
@jelovac yeeeees it would be cool ! =)

**Comment by jelovac** [comment]
Hi guys,

I will find some time to test this tomorrow and if all works as expected will merge.

**Comment by gportes** [comment]
Perfect thanks !

**Pull request merged**
